---
- name: "DevOps / BatsCore / Deploy / Package / Provision core library"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ dops_batscore_application }}"
    sys_package_profiles: "{{ dops_batscore_profiles['core'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"

- name: "DevOps / BatsCore / Deploy / Package / Provision plugin: support"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ dops_batscore_plugins['support'] }}"
    sys_package_profiles: "{{ dops_batscore_profiles['support'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"

- name: "DevOps / BatsCore / Deploy / Package / Provision plugin: assert"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ dops_batscore_plugins['assert'] }}"
    sys_package_profiles: "{{ dops_batscore_profiles['assert'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"

- name: "DevOps / BatsCore / Deploy / Package / Provision plugin: file"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ dops_batscore_plugins['file'] }}"
    sys_package_profiles: "{{ dops_batscore_profiles['file'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
