---
galaxy_info:
  role_name: "dev_opencl"
  author: "serdigital64"
  description: "Manage provision OpenCL development environment"
  company: "none"
  license: "Apache-2.0"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "all"
    - name: "GenericUNIX"
      versions:
        - "all"
  galaxy_tags:
    - "opencl"
dependencies: []
...
