---
- name: "System / Fonts / Initialize"
  ansible.builtin.include_tasks:
    file: "sys_fonts_initialize.yml"

- name: "System / Fonts / Prepare"
  ansible.builtin.include_tasks:
    file: "sys_fonts_prepare.yml"
  when:
    - "'prepare' in sys_fonts"
    - sys_fonts['prepare']

- name: "System / Fonts / Deploy"
  ansible.builtin.include_tasks:
    file: "sys_fonts_deploy.yml"
  when:
    - "'deploy' in sys_fonts"
    - sys_fonts['deploy']

- name: "System / Fonts / Finalize"
  ansible.builtin.include_tasks:
    file: "sys_fonts_finalize.yml"
...
