---
- name: "System / Fonts / Deploy / Configuration"
  ansible.builtin.include_tasks:
    file: "sys_fonts_deploy_config.yml"

- name: "System / Fonts / Deploy / Meslo"
  ansible.builtin.include_tasks:
    file: "sys_fonts_deploy_meslo.yml"
  when:
    - sys_fonts_catalog['meslo'] is defined

- name: "System / Fonts / Deploy / URW"
  ansible.builtin.include_tasks:
    file: "sys_fonts_deploy_urw.yml"
  when:
    - sys_fonts_catalog['urw'] is defined
...
