---
- name: "System / Fonts / Deploy / Configuration / Tools"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ sys_fonts_application['config'] }}"
    sys_package_profiles: "{{ sys_fonts_profiles['config'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
