---
dops_jenkins_base:
  paths: "{{ dops_jenkins_base_common['paths'] }}"
  templates: "{{ dops_jenkins_base_common['templates'] }}"
  access: "{{ dops_jenkins_base_common['access'] }}"
  files:
    logrotate_d: "/etc/logrotate.d/jenkins"
    sysconfig: "/etc/sysconfig/jenkins"

dops_jenkins_profiles:
  distro:
    latest:
      packages:
        - name: "jenkins"

dops_jenkins_repository_custom_yum: []
dops_jenkins_repository_custom_apt:
  - name: "jenkins"
    suite: "binary/"
    url: "https://pkg.jenkins.io/debian-stable"
    pgpkey: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
dops_jenkins_repository_catalog_distro: {}
dops_jenkins_repository_catalog_yum: {}
dops_jenkins_repository_catalog_apt:
  jenkins: true

dops_jenkins_subsystem_profile:
  service: "jenkins"
  states:
    started: "started"
    stopped: "stopped"
    refreshed: "refreshed"
...
