---
sys_user_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "OracleLinux9"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"
  - "MacOSX12"

sys_user_base_common:
  access:
    mode:
      dir: "0700"
      file: "0600"

#sys_user___setup_group: ~
#sys_user___setup_user1: ~
#sys_user___setup_user2: ~
#sys_user___setup_user3: ~
#sys_user___setup_path: ~
sys_user___setup_home: ~
...
