---
- name: "Development / Tools / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ dev_tools_application }}"
    sys_package_profiles: "{{ dev_tools_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
