---
- name: "Development / Tools / Initialize"
  ansible.builtin.include_tasks:
    file: "dev_tools_initialize.yml"

- name: "Development / Tools / Deploy"
  ansible.builtin.include_tasks:
    file: "dev_tools_deploy.yml"
  when:
    - "'deploy' in dev_tools"
    - dev_tools['deploy']

- name: "Development / Tools / Finalize"
  ansible.builtin.include_tasks:
    file: "dev_tools_finalize.yml"
...
