---
sys_subsystem_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "OracleLinux9"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"

sys_subsystem_os_family: >-
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'RedHat' ) or
      ( ansible_distribution == 'AlmaLinux' ) or
      ( ansible_distribution == 'Rocky' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'NotSupported' }}
  {%- endif -%}

sys_subsystem_base_all:
  templates:
    unit_service: "unit.service.j2"

sys_subsystem_application:
  name: "tools"
  type: "distro"
  version: "latest"
  installed: true

sys_subsystem_alert_ansible_managed_file:
  "Warning: This file is automatically generated by the Ansible Role: serdigital64.system.sys_subsystem. Do not modify."

# sys_subsystem___setup_service: ~
...
