---
- name: "DevOps / TFSec / Deploy / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "Required end-state parameters are missing ({{ dops_tfsec_application | default('dops_tfsec_application') }})"
    quiet: true
    that:
      - dops_tfsec_application is defined
      - dops_tfsec_application | length > 0
      - dops_tfsec_application['name'] is defined
      - dops_tfsec_application['type'] is defined
      - dops_tfsec_application['version'] is defined
      - dops_tfsec_application['installed'] is defined

- name: "DevOps / TFSec / Deploy / Package"
  ansible.builtin.include_tasks:
    file: "dops_tfsec_deploy_package.yml"
  when:
    - dops_tfsec_application is defined
...
