---
- name: "System / DConf / Prepare / Paths / Create"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    path: "{{ sys_dconf___prepare_path }}"
    owner: "{{ sys_dconf_base['access']['user']['owner'] }}"
    group: "{{ sys_dconf_base['access']['group']['owner'] }}"
    mode: "{{ sys_dconf_base['access']['mode']['dir'] }}"
  loop:
    - "{{ sys_dconf_base['paths']['dconf_etc'] }}"
    - "{{ sys_dconf_base['paths']['dconf_profile'] }}"
    - "{{ sys_dconf_base['paths']['dconf_db'] }}"
    - "{{ sys_dconf_base['paths']['dconf_db_local'] }}"
    - "{{ sys_dconf_base['paths']['dconf_db_site'] }}"
    - "{{ sys_dconf_base['paths']['dconf_db_distro'] }}"
  loop_control:
    loop_var: "sys_dconf___prepare_path"
...
