---
- name: "System / DConf / Provision / DBs"
  ansible.builtin.include_tasks:
    file: "sys_dconf_provision_dbs.yml"
  when:
    - sys_dconf_db_local is defined
    - sys_dconf_db_local | length > 0
...
