---
- name: "DevOps / GIT / Server / Provision / Repository"
  ansible.builtin.include_tasks:
    file: "dops_git_server_provision_repository.yml"
  loop: "{{ dops_git_server_repositories  }}"
  loop_control:
    loop_var: "dops_git_server___provision_repository"
  when:
    - dops_git_server_repositories is defined
    - dops_git_server_repositories | length > 0
...
