---
- name: "DevOps / GIT / Server / Provision / Repository / Create owner ({{
    dops_git_server___provision_repository['name'] }})"
  vars:
    sys_user:
      setup: true
    sys_user_accounts:
      - name: "{{ dops_git_server___provision_repository['name'] }}"
        home: "{{
          dops_git_server_repository_presets['user_home'] + '/' +
          dops_git_server___provision_repository['name']
          }}"
        description: "{{ dops_git_server_repository_presets['user_geco'] }}"
        shell: "{{ dops_git_server_repository_presets['user_shell'] }}"
        locked: false
        system: false
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_user"

- name: "DevOps / GIT / Server / Provision / Repository / Create directory ({{
      dops_git_server_base['paths']['root'] + '/' + dops_git_server___provision_repository['name'] }})"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    path: "{{
      dops_git_server_base['paths']['root'] + '/' +
      dops_git_server___provision_repository['name']
      }}"
    owner: "{{ dops_git_server___provision_repository['name'] }}"
    group: "{{ dops_git_server___provision_repository['name'] }}"
    mode: "{{ dops_git_server_base['access']['mode']['dir_private'] }}"
  register: "dops_git_server___provision_status"

- name: "DevOps / GIT / Server / Provision / Repository / Initialize repository ({{
      dops_git_server_base['paths']['root'] + '/' + dops_git_server___provision_repository['name'] }})"
  become: true
  ansible.builtin.command:
    chdir: "{{
      dops_git_server_base['paths']['root'] + '/' +
      dops_git_server___provision_repository['name']
      }}"
    argv:
      - "{{ dops_git_server_base['run']['git'] }}"
      - "init"
      - "--bare"
  register: "dops_git_server___provision_git"
  changed_when:
    - dops_git_server___provision_git['rc'] == 0
  when:
    - dops_git_server___provision_status['changed']

- name: "DevOps / GIT / Server / Provision / Repository / Adjust repository ownership ({{
      dops_git_server_base['paths']['root'] + '/' + dops_git_server___provision_repository['name'] }})"
  become: true
  ansible.builtin.file:
    follow: false
    force: true
    unsafe_writes: false
    recurse: true
    state: "directory"
    path: "{{
      dops_git_server_base['paths']['root'] + '/' +
      dops_git_server___provision_repository['name']
      }}"
    owner: "{{ dops_git_server___provision_repository['name'] }}"
    group: "{{ dops_git_server___provision_repository['name'] }}"

- name: "DevOps / GIT / Server / Provision / Repository / Install public keys"
  vars:
    sec_key_ssh:
      setup: true
    sec_key_ssh_remotes:
      - key_string: "{{ dops_git_server___provision_key }}"
        host: "{{ inventory_hostname }}"
        user: "{{ dops_git_server___provision_repository['name'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.security.sec_key_ssh"
  loop: "{{ dops_git_server___provision_repository['public_keys'] }}"
  loop_control:
    loop_var: "dops_git_server___provision_key"
  when:
    - dops_git_server___provision_repository['public_keys'] is defined
    - dops_git_server___provision_repository['public_keys'] | length > 0
...
