---
- name: "DevOps / GIT / Server / Initialize"
  ansible.builtin.include_tasks:
    file: "dops_git_server_initialize.yml"

- name: "DevOps / GIT / Server / Prepare"
  ansible.builtin.include_tasks:
    file: "dops_git_server_prepare.yml"
  when:
    - "'prepare' in dops_git_server"
    - dops_git_server['prepare']

- name: "DevOps / GIT / Server / Deploy"
  ansible.builtin.include_tasks:
    file: "dops_git_server_deploy.yml"
  when:
    - "'deploy' in dops_git_server"
    - dops_git_server['deploy']

- name: "DevOps / GIT / Server / Provision"
  ansible.builtin.include_tasks:
    file: "dops_git_server_provision.yml"
  when:
    - "'provision' in dops_git_server"
    - dops_git_server['provision']

- name: "DevOps / GIT / Server / Finalize"
  ansible.builtin.include_tasks:
    file: "dops_git_server_finalize.yml"
...
