---
- name: Install Package using Group Vars Directory Variables 
  hosts: webservers 
  tasks: 
      - name: Install Tree Command 
        ansible.builtin.dnf:
           name: "{{ package }}"
           state: present
