---
- name: "System / Subsystem / Setup / Custom / Check required parameters (service: {{ sys_subsystem___setup_service['name'] }})"
  ansible.builtin.assert:
    quiet: true
    that:
      - sys_subsystem___setup_service['name'] is defined
      - sys_subsystem___setup_service['type'] is defined

- name: "System / Subsystem / Setup / Custom / Create Unit File (service: {{ sys_subsystem___setup_service['name'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    lstrip_blocks: false
    trim_blocks: false
    group: "{{ sys_subsystem_base['access']['group'] }}"
    mode: "{{ sys_subsystem_base['access']['mode']['file'] }}"
    owner: "{{ sys_subsystem_base['access']['owner'] }}"
    src: "{{ sys_subsystem_base['templates']['unit_service'] }}"
    dest: "{{
      sys_subsystem_base['paths']['units'] + '/' +
      sys_subsystem___setup_service['name'] + '.service'
      }}"
...
