---
- name: "System / Subsystem / Setup / Deploy / Package / Provision tools"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ sys_subsystem_application }}"
    sys_package_profiles: "{{ sys_subsystem_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
