---
- name: "System / Subsystem / Setup / Custom"
  ansible.builtin.include_tasks:
    file: "{{ 'sys_subsystem_setup_custom-' + sys_subsystem_manager + '.yml' }}"
  loop: "{{ sys_subsystem_custom }}"
  loop_control:
    loop_var: "sys_subsystem___setup_service"
  when:
    - sys_subsystem_custom is defined
    - sys_subsystem_custom | length > 0
...
