---
- name: "DevOps / AnsibleLint / Initialize"
  ansible.builtin.include_tasks:
    file: "dops_ansiblelint_initialize.yml"

- name: "DevOps / AnsibleLint / Deploy"
  ansible.builtin.include_tasks:
    file: "dops_ansiblelint_deploy.yml"
  when:
    - dops_ansiblelint['deploy'] is defined
    - dops_ansiblelint['deploy']

- name: "DevOps / AnsibleLint / Finalize"
  ansible.builtin.include_tasks:
    file: "dops_ansiblelint_finalize.yml"
...
