---
- name: "System / Kernel / Setup / Tunables / Network / Tunable: ip_forward"
  become: true
  ansible.posix.sysctl:
    name: "net.ipv4.ip_forward"
    value: "{{
      (sys_kernel_tunables['net']['ipv4']['ip_forward']) |
      ternary( '1', '0' )
      }}"
    state: present
    reload: true
  when:
    - sys_kernel_tunables['net']['ipv4']['ip_forward'] is defined
...
