---
dev_python_base:
  files: "{{ dev_python_base_common['files'] }}"
  access:
    user:
      owner: "root"
    group:
      owner: "root"
    mode:
      dir: "0755"
      file: "0644"
  run:
    python_3_7: &dev_python_base_run_python_3_7
      "/usr/bin/python3.7"
    python_latest: *dev_python_base_run_python_3_7
    python_defaul: *dev_python_base_run_python_3_7

dev_python_profiles:
  distro:
    v3_7: &dev_python_profiles_distro_v3_7
      packages:
        - name: "python3.7"
        - name: "python3.7-venv"
        - name: "python3-pip"
        - name: "python3-setuptools"
        - name: "python3-wheel"
    latest: *dev_python_profiles_distro_v3_7
    default: *dev_python_profiles_distro_v3_7

dev_python_repository_custom_yum: []
dev_python_repository_custom_apt: []

dev_python_repository_catalog_distro: {}
dev_python_repository_catalog_yum: {}
dev_python_repository_catalog_apt: {}
...
