---
dev_python_base:
  files: "{{ dev_python_base_common['files'] }}"
  access:
    user:
      owner: "root"
    group:
      owner: "root"
    mode:
      dir: "0755"
      file: "0644"
  run:
    python_3_9:
      "/usr/bin/python3.9"
    python_3_10: &dev_python_base_run_python_3_10
      "/usr/bin/python3.10"
    python_latest: *dev_python_base_run_python_3_10
    python_defaul: *dev_python_base_run_python_3_10

dev_python_profiles:
  distro:
    v3_9:
      packages:
        - name: "python3.9"
        - name: "python3.9-venv"
        - name: "python3-pip"
        - name: "python3-setuptools"
        - name: "python3-wheel"
    v3_10: &dev_python_profiles_distro_v3_10
      packages:
        - name: "python3.10"
        - name: "python3.10-venv"
        - name: "python3-pip"
        - name: "python3-setuptools"
        - name: "python3-wheel"
    latest: *dev_python_profiles_distro_v3_10
    default: *dev_python_profiles_distro_v3_10

dev_python_repository_custom_yum: []
dev_python_repository_custom_apt: []

dev_python_repository_catalog_distro: {}
dev_python_repository_catalog_yum: {}
dev_python_repository_catalog_apt: {}
...
