---
- name: "Automation / Aplatform64 / Setup / Module / Create site specific A:Platform64 settings ({{
    auto_aplatform64_base['files']['auto_aplatform64_yml'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: false
    unsafe_writes: false
    owner: "{{ auto_ansible_control_base['access']['user']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group']['owner'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['file'] }}"
    src: "{{ auto_aplatform64_base['templates']['auto_aplatform64_yml'] }}"
    dest: "{{ auto_aplatform64_base['files']['auto_aplatform64_yml'] }}"
...
