---
# Define supported platforms
dops_gitlab_server_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "OracleLinux9"

# Group Linux Distributions by family
dops_gitlab_server_os_family: >-
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'RedHat' ) or
      ( ansible_distribution == 'AlmaLinux' ) or
      ( ansible_distribution == 'Rocky' ) or
      ( ansible_distribution == 'OracleLinux' )
  -%}
    {{ 'RedHat' }}
  {%- else -%}
    {{ 'NotSupported' }}
  {%- endif -%}

dops_gitlab_server_owners:
  gitlab_www:
    name: "gitlab-www"
    group: "gitlab-www"
    home: "/var/opt/gitlab/nginx"
  git:
    name: "git"
    group: "git"
    home: "/var/opt/gitlab"
  gitlab_redis:
    name: "gitlab-redis"
    group: "gitlab-redis"
    home: "/var/opt/gitlab/redis"
  gitlab_psql:
    name: "gitlab-psql"
    group: "gitlab-psql"
    home: "/var/opt/gitlab/postgresql"
  registry:
    name: "registry"
    group: "registry"
    home: "/var/opt/gitlab/registry"
  gitlab_prometheus:
    name: "gitlab-prometheus"
    group: "gitlab-prometheus"
    home: "/var/opt/gitlab/prometheus"

# Multiplatform packages
dops_gitlab_server_profiles_common:
  snap: {}
  flatpak: {}
  pip: {}

# Define common paths
dops_gitlab_server_base_common:
  access:
    user:
      owner: "root"
    group:
      owner: "root"
    mode:
      dir: "0755"
      file: "0644"
      private: "0600"
      exe: "0755"
  templates:
    gitlab_rb: "gitlab.rb.j2"
  paths:
    root: "/opt/gitlab"
    var: "/var/opt/gitlab"
    bin: "/opt/gitlab/bin"
    etc: "/etc/gitlab"
  run:
    gitlab_ctl: "/opt/gitlab/bin/gitlab-ctl"
  etc:
    gitlab_rb: "/etc/gitlab/gitlab.rb"
  files: {}

# Build firewall rules based on end-state requirements
dops_gitlab_server_firewall_rules:
  - id: "http"
    service: "http"
    zone: "{{ dops_gitlab_server_firewall['zone'] | default(dops_gitlab_server_firewall_presets['zone']) }}"
    allow: "{{ dops_gitlab_server_subsystem['enabled'] | ternary('enabled', 'disabled') }}"
  - id: "https"
    service: "https"
    zone: "{{ dops_gitlab_server_firewall['zone'] | default(dops_gitlab_server_firewall_presets['zone']) }}"
    allow: "{{ dops_gitlab_server_subsystem['enabled'] | ternary('enabled', 'disabled') }}"

dops_gitlab_server_alert_ansible_managed_file:
  "Warning: This file is automatically generated by the Ansible Role: serdigital64.dops.dops_gitlab_server. Do not modify."
...
