---
# Define platform specific paths
dops_gitlab_server_base:
  paths: "{{ dops_gitlab_server_base_common['paths'] }}"
  etc: "{{ dops_gitlab_server_base_common['etc'] }}"
  files: "{{ dops_gitlab_server_base_common['files'] }}"
  run: "{{ dops_gitlab_server_base_common['run'] }}"
  templates: "{{ dops_gitlab_server_base_common['templates'] }}"
  access: "{{ dops_gitlab_server_base_common['access'] }}"

# Define application package details
dops_gitlab_server_profiles:
  snap: "{{ dops_gitlab_server_profiles_common['snap'] }}"
  flatpak: "{{ dops_gitlab_server_profiles_common['flatpak'] }}"
  pip: "{{ dops_gitlab_server_profiles_common['pip'] }}"
  distro:
    v14:
      supported: true
      origin: "gitlab"
      packages:
        - name: "gitlab-ee"

# Define custom package repositories
dops_gitlab_server_repository_custom_yum:
  - name: "gitlab"
    description: "GitLab repo"
    url: "https://packages.gitlab.com/gitlab/gitlab-ee/el/8/$basearch"
    gpgkey: "https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey/gitlab-gitlab-ee-3D645A26AB9FBD22.pub.gpg"
dops_gitlab_server_repository_custom_apt: []

# Set package repositories states
dops_gitlab_server_repository_catalog_distro: {}
dops_gitlab_server_repository_catalog_yum:
  gitlab: true
dops_gitlab_server_repository_catalog_apt: {}

# Define OS subsystem states
dops_gitlab_server_subsystem_profile:
  service: "gitlab"
  states:
    started: "start"
    stopped: "stop"
    refreshed: "reconfigure"
...
