---
- name: "DevOps / ShellCheck / Deploy / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "Required end-state parameters are missing ({{ dops_shellcheck_application | default('dops_shellcheck_application') }})"
    quiet: true
    that:
      - dops_shellcheck_application is defined
      - dops_shellcheck_application | length > 0
      - dops_shellcheck_application['name'] is defined
      - dops_shellcheck_application['type'] is defined
      - dops_shellcheck_application['version'] is defined
      - dops_shellcheck_application['installed'] is defined

- name: "DevOps / ShellCheck / Deploy / Package"
  ansible.builtin.include_tasks:
    file: "dops_shellcheck_deploy_package.yml"
  when:
    - dops_shellcheck_application is defined
...
