---
- name: "DevOps / ShellCheck / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ dops_shellcheck_application }}"
    sys_package_profiles: "{{ dops_shellcheck_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
