---
- name: "DevOps / ShellCheck / Initialize"
  ansible.builtin.include_tasks:
    file: "dops_shellcheck_initialize.yml"

- name: "DevOps / ShellCheck / Deploy"
  ansible.builtin.include_tasks:
    file: "dops_shellcheck_deploy.yml"
  when:
    - dops_shellcheck['deploy'] is defined
    - dops_shellcheck['deploy']

- name: "DevOps / ShellCheck / Finalize"
  ansible.builtin.include_tasks:
    file: "dops_shellcheck_finalize.yml"
...
