---
- name: "Development / Ruby / Initialize"
  ansible.builtin.include_tasks:
    file: "dev_ruby_initialize.yml"

- name: "Development / Ruby / Deploy"
  ansible.builtin.include_tasks:
    file: "dev_ruby_deploy.yml"
  when:
    - "'deploy' in dev_ruby"
    - dev_ruby['deploy']

- name: "Development / Ruby / Finalize"
  include_tasks: dev_ruby_finalize.yml
...
