---
- name: "DevOps / Jenkins / Control / Subsystem"
  ansible.builtin.include_tasks:
    file: "{{ 'dops_jenkins_control_subsystem-' + dops_jenkins_os_family + '.yml' }}"
  when:
    - dops_jenkins_subsystem is defined
    - dops_jenkins_subsystem['enabled'] is defined
    - dops_jenkins_subsystem['enabled']
    - dops_jenkins_subsystem['status'] is defined
    - dops_jenkins_subsystem_profile['states']
      [dops_jenkins_subsystem['status']] is defined
...
