---
- name: "DevOps / Jenkins / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ dops_jenkins_application }}"
    sys_package_profiles: "{{ dops_jenkins_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
