---
- name: "DevOps / Jenkins / Control / Subsystem / Set enabled state (service: {{
    dops_jenkins_subsystem_profile['service'] }})"
  become: true
  ansible.builtin.systemd:
    no_block: false
    scope: "system"
    name: "{{ dops_jenkins_subsystem_profile['service'] }}"
    enabled: "{{ dops_jenkins_subsystem['enabled'] }}"
...
