---
- name: "Manage Jenkins workers"
  hosts: "jenkins_workers"
  gather_facts: false

  pre_tasks:
    - name: "Manage Jenkins workers / Discover Target Platform"
      ansible.builtin.setup:
        gather_subset: "min"

    - name: "Manage Jenkins workers / Prepare package repositories"
      vars:
        sys_repository:
          prepare: true
          deploy: true
          setup: true
          provision: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"

    - name: "Manage Jenkins workers / Prepare archive manager"
      vars:
        bkp_archive:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.backup.bkp_archive"

    - name: "Manage Jenkins workers / Prepare package installer"
      vars:
        sys_package:
          prepare: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_package"

  tasks:
    - name: "Manage Jenkins workers / Provision OpenJDK 11 for Jenkins"
      vars:
        dev_java:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.development.dev_java"
      when:
        - jenkins_workers_apps['jenkins'] is defined
        - jenkins_workers_apps['jenkins']

    - name: "Manage Jenkins workers / Provision worker users"
      vars:
        sys_user:
          setup: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_user"
...
