---
- name: "Automation / Ansible / Node / Prepare / User / Create"
  vars:
    sys_user:
      setup: true
    sys_user_accounts:
      - name: "{{ auto_ansible_node_owners['node']['user'] }}"
        home: "{{ auto_ansible_node_base['paths']['home'] }}"
        group: "{{ auto_ansible_node_owners['node']['group'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_user"
...
