---
galaxy_info:
  role_name: "sys_kernel"
  author: "serdigital64"
  description: "Manage OS Kernel configuration"
  company: "none"
  license: "Apache-2.0"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "all"
    - name: "GenericUNIX"
      versions:
        - "all"
  galaxy_tags:
    - "kernel"
    - "tuning"
dependencies: []
...
