---
- name: "DevOps / YAMLLint / Deploy / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "Required end-state parameters are missing ({{ dops_yamllint_application | default('dops_yamllint_application') }})"
    quiet: true
    that:
      - dops_yamllint_application is defined
      - dops_yamllint_application | length > 0
      - dops_yamllint_application['name'] is defined
      - dops_yamllint_application['type'] is defined
      - dops_yamllint_application['version'] is defined
      - dops_yamllint_application['installed'] is defined

- name: "DevOps / YAMLLint / Deploy / Package"
  ansible.builtin.include_tasks:
    file: "dops_yamllint_deploy_package.yml"
  when:
    - dops_yamllint_application is defined
...
