---
# Define platform specific paths
sys_dconf_base:
  paths:
    dconf_etc: "/etc/dconf"
    dconf_profile: "/etc/dconf/profile"
    dconf_db: "/etc/dconf/db"
    dconf_db_local: "/etc/dconf/db/local.d"
    dconf_db_site: "/etc/dconf/db/site.d"
    dconf_db_distro: "/etc/dconf/db/distro.d"
  etc:
    profile_user: "/etc/dconf/profile/user"
  run:
    dconf: "/usr/bin/dconf"
  files: "{{ sys_dconf_base_common['files'] }}"
  templates: "{{ sys_dconf_base_common['templates'] }}"
  access: "{{ sys_dconf_base_common['access'] }}"

# Define application package details
sys_dconf_profiles:
  snap: "{{ sys_dconf_profiles_common['snap'] }}"
  flatpak: "{{ sys_dconf_profiles_common['flatpak'] }}"
  distro:
    latest:
      supported: true
      packages:
        - name: "dconf"
        - name: "dconf-editor"
        - name: "dbus-x11"

# Define custom package repositories
sys_dconf_repository_custom_yum: []
sys_dconf_repository_custom_apt: []

# Set package repositories states
sys_dconf_repository_catalog_distro: {}
sys_dconf_repository_catalog_yum: {}
sys_dconf_repository_catalog_apt: {}
...
