---
- name: "Development / OpenCL / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ dev_opencl_application }}"
    sys_package_profiles: "{{ dev_opencl_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
