---
# Define supported platforms
dops_ansiblelint_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "OracleLinux9"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"
  - "MacOSX12"

# Multiplatform packages
dops_ansiblelint_profiles:
  pip:
    latest:
      supported: true
      packages:
        - name: "ansible" # required by ansible-lint
        - name: "ansible-lint"
      options:
        pip:
          owner: "{{ dops_ansiblelint_owners['app']['name'] }}"
          group: "{{ dops_ansiblelint_owners['app']['group'] }}"
          path: "{{ dops_ansiblelint_paths['root'] }}"
          cli: "ansible-lint"

# Define common paths
dops_ansiblelint_base:
  paths:
    root: "{{ dops_ansiblelint_paths['root'] }}"
  run:
    cli: "{{ dops_ansiblelint_paths['root'] + '/ansible-lint' }}"
...
