---
- name: "DevOps / GitLab / Server / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ dops_gitlab_server_application }}"
    sys_package_profiles: "{{ dops_gitlab_server_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
