---
- name: "DevOps / GitLab / Server / Deploy / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "Required end-state parameters are missing ({{ dops_gitlab_server_application | default('dops_gitlab_server_application') }})"
    quiet: true
    that:
      - dops_gitlab_server_application is defined
      - dops_gitlab_server_application | length > 0
      - dops_gitlab_server_application['name'] is defined
      - dops_gitlab_server_application['type'] is defined
      - dops_gitlab_server_application['version'] is defined
      - dops_gitlab_server_application['installed'] is defined

- name: "DevOps / GitLab / Server / Deploy / Package"
  ansible.builtin.include_tasks:
    file: "dops_gitlab_server_deploy_package.yml"
  when:
    - dops_gitlab_server_application is defined
...
