---
- name: "Development / Java / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install OpenJDK"
      vars:
        dev_java:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.development.dev_java"
...
