---
- name: "Database / MySQL / Client / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ db_mysql_client_application }}"
    sys_package_profiles: "{{ db_mysql_client_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
