---
- name: "System / Package / Initialize"
  ansible.builtin.include_tasks:
    file: "sys_package_initialize.yml"

- name: "System / Package / Prepare"
  ansible.builtin.include_tasks:
    file: "sys_package_prepare.yml"
  when:
    - "'prepare' in sys_package"
    - sys_package['prepare']

- name: "System / Package / Provision"
  ansible.builtin.include_tasks:
    file: "sys_package_provision.yml"
  when:
    - "'provision' in sys_package"
    - sys_package['provision']

- name: "System / Package / Finalize"
  ansible.builtin.include_tasks:
    file: "sys_package_finalize.yml"
...
