---
- name: "System / Package / Provision / Type: flatpak / Install / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    that:
      - "'origin' in sys_package___application"
      - sys_package___application['origin'] is not none
      - sys_package___application['origin'] | length > 0
      - "'packages' in sys_package___application"
      - sys_package___application['packages'] is not none
      - sys_package___application['packages'] | length > 0

- name: "System / Package / Provision / Type: flatpak / Install / Install application ({{ sys_package___application['name'] }})"
  become: true
  community.general.flatpak:
    executable: "{{ sys_repository_base['run']['flatpak'] }}"
    name: "{{ sys_package___provision_flatpak['name'] }}"
    method: "system"
    state: "present"
    remote: "{{ sys_package___application['origin'] }}"
  loop: "{{ sys_package___application['packages'] }}"
  loop_control:
    loop_var: "sys_package___provision_flatpak"
...
