---
- name: "System / Package / Prepare / Paths / Create"
  become: true
  ansible.builtin.file:
    follow: false
    unsafe_writes: false
    force: false
    state: "directory"
    owner: "{{ sys_package_base['access']['owner'] }}"
    group: "{{ sys_package_base['access']['group'] }}"
    mode: "{{ sys_package_base['access']['mode']['dir'] }}"
    path: "{{ item }}"
  loop:
    - "{{ sys_package_base['paths']['var'] }}"
    - "{{ sys_package_base['paths']['repository'] }}"
    - "{{ sys_package_base['paths']['staging'] }}"
...
