---
- name: "System / Package / Provision / Type: distro / Platform: {{ ansible_distribution + ansible_distribution_major_version }} / Process packages"
  become: true
  ansible.builtin.apt:
    allow_unauthenticated: false
    autoclean: false
    autoremove: false
    force: false
    force_apt_get: false
    install_recommends: false
    only_upgrade: false
    purge: true
    update_cache: false
    name: "{{
      sys_package___application['packages'] |
      map( attribute = 'name' ) |
      list()
      }}"
    state: "{{
      (sys_package_application['installed']) |
      ternary(
        'present',
        'absent'
      )
      }}"
...
