---
- name: "System / Package / Provision / Type: deb / Dowload Package to the Repository (url: {{
    sys_package___application['origin'] + '/' + sys_package___provision_deb['file'] }})"
  vars:
    sys_package___download_headers: "
      {%- if(sys_package___provision_deb['referer'] is defined) -%}
        {{ { 'referer': sys_package___provision_deb['referer'] } }}
      {%- else -%}
        {{ {} }}
      {%- endif -%}
      "
    sys_package___download_url: "{{ sys_package___application['origin'] }}"
    sys_package___download_file: "{{ sys_package___provision_deb['file'] }}"
    sys_package___download_dest: "{{ sys_package___application['repository'] }}"
  ansible.builtin.include_tasks:
    file: "sys_package_provision_download.yml"

- name: "System / Package / Provision / Type: deb / Install package ({{ sys_package___provision_deb['file'] }})"
  become: true
  ansible.builtin.apt:
    allow_unauthenticated: false
    autoclean: false
    autoremove: false
    force: false
    force_apt_get: false
    install_recommends: false
    only_upgrade: false
    purge: true
    update_cache: false
    deb: "{{ sys_package___application['repository'] + '/' + sys_package___provision_deb['file'] }}"
    state: "present"
...
