---
- name: "System / Package / Provision / Type: distro / Install / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    that:
      - "'packages' in sys_package___application"
      - sys_package___application['packages'] is not none
      - sys_package___application['packages'] | length > 0
      - "'name' in sys_package___application['packages'][0]"
      - sys_package___application['packages'][0]['name'] | length > 0

- name: "System / Package / Provision / Type: distro / Install / Platform: {{ ansible_distribution + ansible_distribution_major_version }}"
  ansible.builtin.include_tasks:
    file: "{{
      'sys_package_provision_type-distro-' +
        ansible_distribution +
        ansible_distribution_major_version +
        '.yml'
      }}"
...
