---
- name: "System / Package / Provision / Paths / Create"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    state: "directory"
    mode: "{{ sys_package___provision_paths['mode'] | default( omit ) }}"
    owner: "{{ sys_package___provision_paths['owner'] | default( omit ) }}"
    group: "{{ sys_package___provision_paths['group'] | default( omit ) }}"
    path: "{{ sys_package___provision_paths['target'] }}"
  loop: "{{ sys_package___application['paths'] }}"
  loop_control:
    loop_var: "sys_package___provision_paths"
...
