---
- name: "System / Package / Provision / Type: pip / Uninstall / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "Required parameters are missing ({{ sys_package___application }})"
    quiet: true
    that:
      - sys_package___application['packages'] is defined
      - sys_package___application['packages'] | length > 0
      - sys_package___application['packages'][0]['name'] is defined
      - sys_package___application['packages'][0]['name'] | length > 0
      - sys_package___application['options'] is defined
      - sys_package___application['options']['pip'] is defined
      - sys_package___application['options']['pip']['owner'] is defined
      - sys_package___application['options']['pip']['owner'] | length > 0
      - sys_package___application['options']['pip']['group'] is defined
      - sys_package___application['options']['pip']['group'] | length > 0
      - sys_package___application['options']['pip']['path'] is defined
      - sys_package___application['options']['pip']['path'] | length > 0

- name: "System / Package / Provision / Type: pip / Uninstall / Remove location"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "absent"
    path: "{{ sys_package___application['options']['pip']['path'] }}"
...
