---
- name: "System / Package / Provision / CleanUp / Files"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    state: "absent"
    path: "{{ sys_package___provision_file }}"
  loop: "{{ sys_package___application['cleanup'] }}"
  loop_control:
    loop_var: "sys_package___provision_file"
...
