---
- name: "System / Package / Provision / Type: deb / Uninstall / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    that:
      - "'packages' in sys_package___application"
      - sys_package___application['packages'] is not none
      - sys_package___application['packages'] | length > 0

- name: "System / Package / Provision / Type: deb / Uninstall / Remove packages"
  ansible.builtin.include_tasks:
    file: "sys_package_provision_type-distro-uninstall.yml"
  register: "sys_package___provision_result"

- name: "System / Package / Provision / Type: deb / Uninstall / CleanUp"
  ansible.builtin.include_tasks:
    file: "sys_package_provision_cleanup.yml"
  when:
    - sys_package___provision_result['changed']
    - "'cleanup' in sys_package___application"
    - sys_package___application['cleanup'] is not none
    - sys_package___application['cleanup'] | length > 0
...
