---
galaxy_info:
  role_name: "sys_shell"
  author: "serdigital64"
  description: "Manage Unix shells provisioning"
  company: "none"
  license: "Apache-2.0"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "all"
    - name: "GenericUNIX"
      versions:
        - "all"
  galaxy_tags:
    - "bash"
    - "zsh"
    - "csh"
    - "ksh"
    - "shell"
dependencies: []
...
