---
sys_package_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "OracleLinux9"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"
  - "MacOSX12"

sys_package_os_family: >-
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'RedHat' ) or
      ( ansible_distribution == 'AlmaLinux' ) or
      ( ansible_distribution == 'Rocky' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- elif
      ( ansible_distribution == 'MacOSX' )
  -%}
    {{ 'MacOSX' }}
  {%- else -%}
    {{ 'NotSupported' }}
  {%- endif -%}

sys_package_base_common:
  paths:
    var: "{{ sys_package_paths['root_var'] }}"
    staging: "{{ sys_package_paths['root_var'] + '/staging' }}"
    repository: "{{ sys_package_paths['root_var'] + '/repository' }}"
  templates:
    pip_loader_sh: "pip_loader.sh.j2"

# Configurable parameters for package managers
sys_package_configuration:
  download:
    timeout: "30"
  binary:
    timeout: "30"
  deb:
    timeout: "30"
  rpm:
    timeout: "30"
  dnf:
    lock_timeout: "10"

sys_package_flavours:
  - "binary"
  - "brew"
  - "deb"
  - "distro"
  - "flatpak"
  - "git"
  - "pip"
  - "rpm"
  - "snap"

# Basic Python modules for venv
sys_package_python_base:
  - "pip"
  - "setuptools"
  - "wheel"

# Select the target application from the profile list
sys_package___application:
  supported: "{{ sys_package_application['supported'] | default(true) }}"
  type: "{{ sys_package_application['type'] }}"
  name: "{{ sys_package_application['name'] }}"
  version: "{{ sys_package_application['version'] }}"
  packages: "{{
    sys_package_profiles[
    sys_package_application['type']
    ][
    sys_package_application['version']
    ][
    'packages'
    ]
    }}"
  origin: "{{
    sys_package_profiles[
    sys_package_application['type']
    ][
    sys_package_application['version']
    ][
    'origin'
    ] | default( '' )
    }}"
  options: "{{
    sys_package_profiles[
    sys_package_application['type']
    ][
    sys_package_application['version']
    ][
    'options'
    ] | default( {} )
    }}"
  promotion: "{{
    sys_package_profiles[
    sys_package_application['type']
    ][
    sys_package_application['version']
    ][
    'promotion'
    ] | default( [] )
    }}"
  paths: "{{
    sys_package_profiles[
    sys_package_application['type']
    ][
    sys_package_application['version']
    ][
    'paths'
    ] | default( [] )
    }}"
  cleanup: "{{
    sys_package_profiles[
    sys_package_application['type']
    ][
    sys_package_application['version']
    ][
    'cleanup'
    ] | default( {} )
    }}"
  script: "{{
    sys_package_profiles[
    sys_package_application['type']
    ][
    sys_package_application['version']
    ][
    'script'
    ] | default( {} )
    }}"
  staging: "{{
    sys_package_base['paths']['staging'] + '/' +
    sys_package_application['name']
    }}"
  repository: "{{
    sys_package_base['paths']['repository'] + '/' +
    sys_package_application['name']
    }}"

sys_package___initialize_status: ~
sys_package___provision_repository_status: ~
sys_package___provision_script_status: ~
sys_package___provision_script_file: ~
sys_package___provision_download_status: ~
sys_package___provision_result: ~
sys_package___provision_uncompress: ~
sys_package___provision_test: ~
sys_package___provision_task_download: ~
# sys_package___provision_paths: ~
# sys_package___provision_binary: ~
# sys_package___provision_check: {}
# sys_package___provision_path: []
# sys_package___provision_promote: ~
# sys_package___provision_file: ~
# sys_package___provision_flatpak: ~
# sys_package___provision_snap: ~
# sys_package___provision_deb: ~
# sys_package___provision_rpm: ~

sys_package_alert_ansible_managed_file:
  "Warning: This file is automatically generated by the Ansible Role: serdigital64.system.sys_package. Do not modify."
...
