---
# Define supported platforms
db_mysql_server_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "OracleLinux9"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"

# Group Linux Distributions by family
db_mysql_server_os_family: >-
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'RedHat' ) or
        ( ansible_distribution == 'AlmaLinux' ) or
        ( ansible_distribution == 'Rocky' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- elif
      ( ansible_distribution == 'Debian' )
  -%}
    {{ 'Debian' }}
  {%- else -%}
    {{ 'NotSupported' }}
  {%- endif -%}

# Multiplatform packages
db_mysql_server_profiles_common:
  snap: {}
  flatpak: {}

# Define common paths
db_mysql_server_base_common:
  access: {}
  templates: {}
  paths: {}
  files: {}
  run: {}
  etc: {}
...
