---
- name: "System / Shell / Initialize"
  ansible.builtin.include_tasks:
    file: "sys_shell_initialize.yml"

- name: "System / Shell / Deploy"
  ansible.builtin.include_tasks:
    file: "sys_shell_deploy.yml"
  when:
    - sys_shell['deploy'] is defined
    - sys_shell['deploy']

- name: "System / Shell / Setup"
  ansible.builtin.include_tasks:
    file: "sys_shell_setup.yml"
  when:
    - sys_shell['setup'] is defined
    - sys_shell['setup']

- name: "System / Shell / Finalize"
  ansible.builtin.include_tasks:
    file: "sys_shell_finalize.yml"
...
