---
- name: "System / Shell / Deploy / App / Deploy KSH"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ sys_shell_application['ksh'] }}"
    sys_package_profiles: "{{ sys_shell_profiles['ksh'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
