---
- name: "System / Shell / Deploy / App / Deploy CSH"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ sys_shell_application['csh'] }}"
    sys_package_profiles: "{{ sys_shell_profiles['csh'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
