---
- name: "System / GUI / Cinnamon / Prepare / Paths / Create"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    path: "{{ sys_gui_cinnamon___prepare_path }}"
    owner: "{{ sys_gui_cinnamon_base['access']['user']['owner'] }}"
    group: "{{ sys_gui_cinnamon_base['access']['group']['owner'] }}"
    mode: "{{ sys_gui_cinnamon_base['access']['mode']['dir'] }}"
  loop:
    - "{{ sys_gui_cinnamon_base['paths']['var'] }}"
  loop_control:
    loop_var: "sys_gui_cinnamon___prepare_path"
...
