---
- name: "System / GUI / Cinnamon / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ sys_gui_cinnamon_application }}"
    sys_package_profiles: "{{ sys_gui_cinnamon_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
