---
galaxy_info:
  role_name: "sys_user"
  author: "serdigital64"
  description: "Manage Unix users and groups provisioning"
  company: "none"
  license: "Apache-2.0"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "all"
    - name: "GenericUNIX"
      versions:
        - "all"
  galaxy_tags:
    - "user"
    - "group"
dependencies: []
...
