---
- name: "System / User / Setup / Group / Create"
  become: true
  ansible.builtin.group:
    state: "present"
    name: "{{ sys_user___setup_group['name'] }}"
    system: "{{ sys_user___setup_group['system'] | default( omit ) }}"
    gid: "{{ sys_user___setup_group['gid'] | default( omit ) }}"
  loop: "{{ sys_user_groups }}"
  loop_control:
    loop_var: "sys_user___setup_group"
...
