---
- name: "System / User / Setup / User / Create primary group ({{ sys_user___setup_user1['group'] }})"
  become: true
  ansible.builtin.group:
    name: "{{ sys_user___setup_user1['group'] | default( sys_user___setup_user1['name'] ) }}"
    state: "present"
  loop: "{{ sys_user_accounts }}"
  loop_control:
    loop_var: "sys_user___setup_user1"

- name: "System / User / Setup / User / Create Account ({{ sys_user___setup_user2['name'] }})"
  become: true
  ansible.builtin.user:
    create_home: true
    generate_ssh_key: false
    state: "present"
    name: "{{ sys_user___setup_user2['name'] }}"
    system: "{{ sys_user___setup_user2['system'] | default( omit ) }}"
    group: "{{ sys_user___setup_user2['group'] | default( sys_user___setup_user2['name'] ) }}"
    comment: "{{ sys_user___setup_user2['description'] | default( omit ) }}"
    home: "{{ sys_user___setup_user2['home'] | default( omit ) }}"
    shell: "{{ sys_user___setup_user2['shell'] | default( omit ) }}"
    groups: "{{ sys_user___setup_user2['groups'] | default( omit ) }}"
    uid: "{{ sys_user___setup_user2['uid'] | default( omit ) }}"
  loop: "{{ sys_user_accounts }}"
  loop_control:
    loop_var: "sys_user___setup_user2"
...
