---
sys_sudo_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "OracleLinux9"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"
  - "MacOSX12"

sys_sudo_profiles:
  distro:
    latest:
      packages:
        - name: "sudo"

sys_sudo_base:
  etc:
    sudoers: "/etc/sudoers"
  run:
    sudo: "/usr/bin/sudo"
    visudo: "/usr/sbin/visudo"

# sys_sudo___setup_item
...
