---
- name: "DevOps / Molecule / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ dops_molecule_application }}"
    sys_package_profiles: "{{ dops_molecule_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
