---
- name: "DevOps / GIT / Client / Provision / Repository"
  ansible.builtin.include_tasks:
    file: "dops_git_client_provision_repository.yml"
  loop: "{{ dops_git_client_repositories }}"
  loop_control:
    loop_var: "dops_git_client___provision_repo"
  when:
    - dops_git_client_repositories is defined
    - dops_git_client_repositories | length > 0
...
