---
dev_java_base:
  run:
    java: "/usr/bin/java"

dev_java_profiles:
  distro:
    v1_8:
      packages:
        - name: "openjdk-8-jdk"
    v1_11:
      packages:
        - name: "openjdk-11-jdk"
    v1_18: &dev_java_profiles_distro_v18
      source: "updates"
      packages:
        - name: "openjdk-18-jdk"
    latest: *dev_java_profiles_distro_v18

dev_java_repository_custom_yum: []
dev_java_repository_custom_apt: []

dev_java_repository_catalog_distro: {}
dev_java_repository_catalog_yum: {}
dev_java_repository_catalog_apt: {}
...
