---
- name: "System / MC / Prerequisite / Prepare package managers {{ sys_repository_managers }}"
  vars:
    sys_repository:
      prepare: true
      deploy: true
      setup: true
      provision: true
    sys_repository_managers:
      flatpak: "{{ sys_mc_application['type'] == 'flatpak' }}"
      snap: "{{ sys_mc_application['type'] == 'snap' }}"
      git: "{{ sys_mc_application['type'] == 'git' }}"
      pip: "{{ sys_mc_application['type'] == 'pip' }}"
      brew: "{{ sys_mc_application['type'] == 'brew' }}"
    sys_repository_catalog_distro: "{{ sys_mc_repository_catalog_distro }}"
    sys_repository_catalog_yum: "{{ sys_mc_repository_catalog_yum }}"
    sys_repository_catalog_apt: "{{ sys_mc_repository_catalog_apt }}"
    sys_repository_custom_yum: "{{ sys_mc_repository_custom_yum }}"
    sys_repository_custom_apt: "{{ sys_mc_repository_custom_apt }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_repository"

- name: "System / MC / Prerequisite / Prepare archive manager"
  vars:
    bkp_archive:
      deploy: true
  ansible.builtin.include_role:
    name: "serdigital64.backup.bkp_archive"

- name: "System / MC / Prerequisite / Prepare package installer"
  vars:
    sys_package:
      prepare: true
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
