---
- name: "System / Sudo / Initialize"
  ansible.builtin.include_tasks:
    file: "sys_sudo_initialize.yml"

- name: "System / Sudo / Deploy"
  ansible.builtin.include_tasks:
    file: "sys_sudo_deploy.yml"
  when:
    - "'deploy' in sys_sudo"
    - sys_sudo['deploy']

- name: "System / Sudo / Setup"
  ansible.builtin.include_tasks:
    file: "sys_sudo_setup.yml"
  when:
    - "'setup' in sys_sudo"
    - sys_sudo['setup']

- name: "System / Sudo / Finalize"
  ansible.builtin.include_tasks:
    file: "sys_sudo_finalize.yml"
...
