---
galaxy_info:
  role_name: "dops_molecule"
  author: "serdigital64"
  description: "Manage provisioning of Molecule"
  company: "none"
  license: "Apache-2.0"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "all"
    - name: "GenericUNIX"
      versions:
        - "all"
  galaxy_tags:
    - "ansible"
    - "molecule"
dependencies: []
...
