download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/serdigital64-automation-3.2.6.tar.gz
format_version: 1.0.0
name: automation
namespace: serdigital64
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.2.6
version_url: /api/v3/plugin/ansible/content/published/collections/index/serdigital64/automation/versions/3.2.6/
