---
galaxy_info:
  role_name: "auto_ansible_node"
  author: "serdigital64"
  description: "Automate the management of Ansible Managed Nodes"
  company: "none"
  license: "Apache-2.0"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "all"
    - name: "GenericUNIX"
      versions:
        - "all"
  galaxy_tags:
    - "ansible"
dependencies: []
...
