---
- name: "System / Repository / Deploy / Snap / CLI"
  become: true
  ansible.builtin.package:
    state: "present"
    name: "{{ sys_repository_packages['snap'] }}"
  register: "sys_repository___deploy_result"

- name: "System / Repository / Deploy / Snap / Enable SnapD"
  become: true
  ansible.builtin.command:
    argv:
      - "{{ sys_repository_base['run']['systemctl'] }}"
      - "enable"
      - "--now"
      - "snapd.socket"
  when:
    - sys_repository___deploy_result['changed']
  changed_when: false

- name: "System / Repository / Deploy / Snap / Enable classic mode"
  become: true
  ansible.builtin.file:
    force: true
    src: "{{ sys_repository_base['paths']['snap_var'] }}"
    path: "{{ sys_repository_base['paths']['snap_root'] }}"
    state: "link"
...
