---
- name: "System / Repository / Deploy / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "required parameters are missing ({{
      sys_repository_managers | default('sys_repository_managers') }})"
    quiet: true
    that:
      - sys_repository_managers is defined
      - sys_repository_managers | length > 0

- name: "System / Repository / Deploy / Tools"
  ansible.builtin.include_tasks:
    file: "sys_repository_deploy_tools.yml"
  when:
    - ansible_system == "Linux"

- name: "System / Repository / Deploy / Distro"
  include_tasks:
    file: "{{ 'sys_repository_deploy_distro.yml' }}"
  when:
    - ansible_system == "Linux"
    - sys_repository_packages['distro'] | length > 0

- name: "System / Repository / Deploy / FlatPak"
  ansible.builtin.include_tasks:
    file: "sys_repository_deploy_flatpak.yml"
  when:
    - ansible_system == "Linux"
    - sys_repository_managers['flatpak'] is defined
    - sys_repository_managers['flatpak']

- name: "System / Repository / Deploy / Snap"
  ansible.builtin.include_tasks:
    file: "{{ 'sys_repository_deploy_snap-' + sys_repository_os_family + '.yml' }}"
  when:
    - ansible_system == "Linux"
    - sys_repository_managers['snap'] is defined
    - sys_repository_managers['snap']

- name: "System / Repository / Deploy / GIT"
  ansible.builtin.include_tasks:
    file: "sys_repository_deploy_git.yml"
  when:
    - (sys_repository_managers['git'] is defined and sys_repository_managers['git']) or
      (sys_repository_managers['brew'] is defined and sys_repository_managers['brew'])

- name: "System / Repository / Deploy / PIP"
  ansible.builtin.include_tasks:
    file: "sys_repository_deploy_pip.yml"
  when:
    - ansible_system == "Linux"
    - sys_repository_managers['pip'] is defined
    - sys_repository_managers['pip']

- name: "System / Repository / Deploy / Brew"
  ansible.builtin.include_tasks:
    file: "sys_repository_deploy_brew.yml"
  when:
    - sys_repository_managers['brew'] is defined
    - sys_repository_managers['brew']
...
