---
- name: "System / Repository / Provision / FlatPak / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    that:
      - sys_repository___provision_repo_flatpak['name'] is defined
      - sys_repository___provision_repo_flatpak['name'] | length > 0
      - sys_repository___provision_repo_flatpak['url'] is defined
      - sys_repository___provision_repo_flatpak['url'] | length > 0

- name: "System / Repository / Provision / FlatPak / Detect installed repositories"
  ansible.builtin.command:
    argv:
      - "{{ sys_repository_base['run']['flatpak'] }}"
      - "remotes"
  register: "sys_repository___provision_test"
  changed_when: false

- name: "System / Repository / Provision / FlatPak / Register repository definition (repo: {{ sys_repository___provision_repo_flatpak['name'] }})"
  become: true
  ansible.builtin.command:
    argv:
      - "{{ sys_repository_base['run']['flatpak'] }}"
      - "--system"
      - "remote-add"
      - "{{ sys_repository___provision_repo_flatpak['name'] }}"
      - "{{ sys_repository___provision_repo_flatpak['url'] }}"
  register: "sys_repository___provision_result"
  changed_when:
    - sys_repository___provision_result['rc'] == 0
  when:
    - not sys_repository___provision_test['stdout_lines'] is search( sys_repository___provision_repo_flatpak['name'] )
...
