---
- name: "System / Repository / Prepare / Distro / Update repository cache"
  become: true
  no_log: true
  failed_when: false
  ansible.builtin.command:
    argv:
      - "{{ sys_repository_base['run']['apt_get'] }}"
      - "--quiet"
      - "update"
  changed_when: false
...
