---
- name: "System / Repository / Provision / Brew / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    that:
      - sys_repository___provision_repo_brew['source'] is defined
      - sys_repository___provision_repo_brew['source'] | length > 0

- name: "System / Repository / Provision / Brew / Add Tap"
  become: true
  ansible.builtin.command:
    chdir: "{{ sys_repository_base['paths']['homebrew_home'] }}"
    argv:
      - "{{ sys_repository_base['run']['su'] }}"
      - "-l"
      - "{{ sys_repository_owners['homebrew']['user'] }}"
      - "-c"
      - "{{ sys_repository_base['run']['brew'] + ' tap ' + sys_repository___provision_repo_brew['source'] }}"
  changed_when: false
...
